CREATE TABLE "cadastro" (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"nome" TEXT NOT NULL,
	"cpf" TEXT NOT NULL,
	"email" TEXT NOT NULL,
	"dataNascimento" TEXT NOT NULL,
	"titulo" TEXT,
	"categoria" TEXT NOT NULL,
	"descricaoservico" TEXT NOT NULL,
	"rua" TEXT NOT NULL,
	"bairro" TEXT NOT NULL,
	"cidade" TEXT NOT NULL,
	"estado" TEXT NOT NULL,
	"cep" TEXT NOT NULL,
	"tiporedesocial1" TEXT,
	"link1" TEXT,
    "tiporedesocial2" TEXT,
	"link2" TEXT,
	"tiporedesocial3" TEXT,
	"link3" TEXT,
	"numero1" TEXT NOT NULL,
	"numero2" TEXT,
	"numero3" TEXT,
	"numero4" TEXT
);
